turtle_node:
  ros__parameters:

    turtle_name: "turtle1"

    target_x: 10.0
    target_y: 10.0
    linear_gain: 1.5
    angular_gain: 6.0
    distance_tolerance: 0.1
    angle_tolerance: 0.05
    loop_rate: 20